### ISSUE TITLE
关于“如何购买服务器”

### ISSUE THREAD

**Issue by HydrogenDeuterium** [Mhy278/MinecraftServerHostGuide#14]
现在 阿里云/腾讯云/其他xx云的 服务器感觉来源更好，而且是第一方服务，是否考虑加进去？

淘宝再怎么说终究还是第三方的，感觉不如第一方

**Comment by Mhy278** [comment]
大厂云除了有独立IP之外，其他的各方面都不如圈内专门做MC的服务商，考虑到本教程的对象是刚入坑的小白，售后解答的效率和专业性也是很重要的，所以并没有推荐大厂云产品。
