### ISSUE TITLE
关于 ”服务端核心“

### ISSUE THREAD

**Issue by HydrogenDeuterium** [Mhy278/MinecraftServerHostGuide#15]
https://github.com/orgs/CatServer/repositories 现在似乎已经死了 连仓库都找不到。

**Comment by Mhy278** [comment]
Catserver仓库地址存在诸多历史遗留问题，目前的仓库为https://github.com/Luohuayu/CatServer ，考虑到未来还可能会发生变更以及如若变更地址可能产生的纠纷，因此姑且不做更改。

**Comment by Mhy278** [comment]
鉴于CatServer项目仓库地址至今仍未发生变动，且开发进展持续稳定可观，现已将教程中的链接修改为目前的仓库地址。
