### ISSUE TITLE
关于核心和优化的一点看法

### ISSUE THREAD

**Issue by noionion** [Mhy278/MinecraftServerHostGuide#16]
偶然看到这样一个文档感觉还是不错的，但对于核心方面是不是忽略了原版核心？

而且对于生电玩家而言paper貌似十分不友好，原版的各种特性修改的过多了。过度的推荐paper其实对于想开生电服的小白腐竹不太友好，一些在生电交流群里问paper机器的很多也基本解答不了，只能说paper没办法

以及优化方面插件用mcdr插件的扫地机可能就不是负优化了，而且扫地机对于产生大规模掉落物（比如世吞）的机器一定程度上是非常有用的，我觉得不应该以偏概全

**Comment by Mhy278** [comment]
非常感谢您提出的问题。
很显然我们的教程只是面向刚刚接触我的世界联机的爱好者，很大一部分可能是喜欢我的世界这个游戏，从而想要自己开一个联机服务器和好朋友一起玩的简单目的。因此我们认为，相比原版核心的新版本或者纯净体验来说，或许一些完成度更高、扩展内容更丰富的服务端会更适合这类群体。再者也考虑到一些第三方的服务端会对一些常见的高频或复杂计算有一定程度的优化，适合预算不高而妥协购买的低配置服务器运行。所以对于原版核心仅仅是在第一单元第一节中简要提到，并没有深入讲解。
对于生电玩家来说，我个人是红石渣所以真的很崇拜会玩红石的玩家。但是根据我们团队的理解，生电已经是比较核心或者有一定门槛和深度的游戏内容，已经不属于我们教程教授的范畴了。同时，生电利用的某些特性确实是会和第三方服务端的优化冲突的，所以的确存在你所提到的Paper对生电不友好的问题。正如上一段所说，一些萌新腐竹可能预算并不是很充裕，选择优化比较激进的第三方服务端也是一种对稳定性的妥协，这个问题就要看腐竹自己的选择和权衡了。专业的人干专业的事，我相信生电玩家和腐竹肯定非常熟悉生电服所需要的服务器环境和配置要求。
再次感谢您提出的问题，谢谢。

**Comment by noionion** [comment]
也是，不然在原版优化方面我还是更加推荐原版端+carpet及其扩展模组+元素周期表那几个优化模组来做优化，但都有一定的门槛
