### ISSUE TITLE
建议把 原版服务端 和 Forge服务端 分开来

### ISSUE THREAD

**Issue by Taskeren** [Mhy278/MinecraftServerHostGuide#2]
虽然Forge服务器是通过原版安装来的，但是也是完全不同的两种服务端呐。

还有，可以出一个Forge服务端安装教学。

**Comment by violetice** [comment]
其实可以用Linux来搭建，还能用nginx的反代来上个域名。相同硬件情况下，Linux的系统开销更小。也就比win server会便宜。因为考虑到系统开销，win server可能还需要上一个档位才行。

**Comment by Mhy278** [comment]
目前的模组服务端主要使用Catserver和Mohist，均有自动化安装功能，在未来的更新中会考虑加入Forge原版安装教学。
Linux使用难度大，不建议新手使用，本教程不作考虑。
